reddit_on_rails/config/routes.rb
Rails.application.routes.draw do

  resources :subs
  resources :posts, only: [:new, :create, :edit, :update, :show, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_on_rails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :user_id, presence: true

  belongs_to :author, class_name: 'User', foreign_key: :user_id, primary_key: :id

  has_many :post_subs#, class_name: 'PostSub', foreign_key: :post_id
  has_many :subs, through: :post_subs, source: :sub

  has_many :comments
end

reddit_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids => [])
  end
end

reddit_on_rails/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_on_rails/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label>Title
  <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>"
  </label>

  <input type="hidden" name="post[sub_ids][]" value="">
  <p>Which subs do you want to post to?</p>
    <% Sub.all.each do |subred| %>
      <input type="checkbox"
        name="post[sub_ids][]"
        value="<%= subred.id %>"
        <%= "checked" if @post.sub_ids.include?(subred.id) %>
        /><%= subred.title %><br>
    <% end %>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <input type="submit" name="" value="Update Post">
</form>

reddit_on_rails/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>

  <label>Title
  <input type="text" name="post[title]" value="">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="">
  </label>

  <input type="hidden" name="post[sub_ids][]" value="">
  <p>Which subs do you want to post to?</p>
    <% Sub.all.each do |subred| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= subred.id %>"><%= subred.title %><br>
    <% end %>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label>

  <input type="submit" name="" value="New Post">
</form>

reddit_on_rails/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<h5><%= "by #{@post.author.username}" %></h5>

<p><%= @post.content %></p>

<a href="<%= edit_post_url(@post) %>">Edit Post</a>


<h3>Comments</h3>
<ul>
  <% @post.comments.each do |comment| %>
    <li>
      <%= comment.content %>
      <%= button_to "Remove Content", comment_url(comment), method: :delete %>
    </li>

  <% end %>
</ul>

<h3>Add Comment</h3>

<form action="<%= post_comments_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">

  <label>Write your comment:
  <input type="text" name="comment[content]" value="">
  </label>

  <input type="submit" name="" value="Submit comment">
</form>