reddit_on_rails/config/routes.rb
Rails.application.routes.draw do

  resources :subs
  resources :posts, only: [:new, :create, :edit, :update, :show, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_on_rails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :user_id, presence: true

  belongs_to :moderator, class_name: 'User', foreign_key: :user_id, primary_key: :id
  has_many :post_subs#, class_name: 'PostSub', foreign_key: :sub_id
  has_many :posts, through: :post_subs, source: :post
end

reddit_on_rails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in!

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end

  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit_on_rails/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_on_rails/app/views/subs/edit.html.erb
<h1>Edit Subreddit</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label>Title
  <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Update Subreddit">
</form>

reddit_on_rails/app/views/subs/index.html.erb
<h1>Subreddit Index</h1>

<% Sub.all.each do |sub| %>
  <ul>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a>:  <%= sub.description %></li>
  </ul>
<% end %>


<a href="<%= new_sub_url %>">Add New Sub</a> 

reddit_on_rails/app/views/subs/new.html.erb
<h1>New Subreddit</h1>

<form action="/subs" method="post">
  <%= auth_token %>

  <label>Title
  <input type="text" name="sub[title]" value="">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" name="" value="Create Subreddit">
</form>

reddit_on_rails/app/views/subs/show.html.erb
<h2> <%= @sub.title %> </h2>

<h5>by <%= @sub.moderator.username %></h5>

<h4><%= @sub.description %></h4>

<a href="<%= new_post_url %>">New Post</a>

<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
<a href="<%= subs_url %>">All Subs</a>